application:
  geometry:
    type: Polygon
    coordinates: [[[92.172,9.537],[92.172,28.547],[101.170,28.547],[101.170,9.537],[92.172,9.537]]]
  name: Myanmar
  layers:
  - name: "Accessibility"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "accessability"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
  - name: "Population Density 2008"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "lspop_2008"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
  - name: "Global Land Cover 2009"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "globcover_2009"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
  - name: "Global Cropland"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "gl_cropland"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
  - name: "Global Pasture Land"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "gl_pasture"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
  - name: "Global Forest Change Loss Year 2001-2016 (Hansen et al.)"
    url: "https://gis2.onemapmyanmar.info/gis2/services/hansen_lossyear_gfc2016_transp/MapServer/WMSServer"
    wms_options:
    - epsg: 102100
    - format: "image/jpeg"
    - layers: "0"
    - transparent: true
    - abstract: "<p>Results from time-series analysis of Landsat images characterizing forest extent and change.</p><p>Trees are defined as vegetation taller than 5m in height and are expressed as a percentage per output grid cell as ‘2000 Percent Tree Cover’. ‘Forest Cover Loss’ is defined as a stand-replacement disturbance, or a change from a forest to non-forest state, during the period 2000–2016. ‘Forest Cover Gain’ is defined as the inverse of loss, or a non-forest to forest change entirely within the period 2000–2012. ‘Forest Loss Year’ is a disaggregation of total ‘Forest Loss’ to annual time scales.</p><p>Source: <a href='http://science.sciencemag.org/content/342/6160/850' target='_blank'>Hansen et al. 2013</a></p>"
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
  - name: "Mining Areas (Connette et al.)"
    url: "https://gis2.onemapmyanmar.info/gis2/services/mining_myanmar_mimu_2016/MapServer/WMSServer"
    wms_options:
    - epsg: 102100
    - format: "image/jpeg"
    - layers: "Mining Myanmar"
    - transparent: true
    - abstract: "<p>This is a dataset of possible mining areas in Myanmar that was digitized from a systematic search of high-resolution imagery available on Google Earth and Bing Aerial. Digitizing took place in late 2015 and early 2016 with the most recent imagery available (usually 2014 or 2015). A field in the attribute table called 'Certainty' indicates the how confident we were that the digitized polygon is a mine, rather than some other type of ground disturbance.</p><p>Source: <a href='http://www.mdpi.com/2072-4292/8/11/912/htm' target='_blank'>Connette et al. 2016</a></p>"
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
  spatial_accuracy:
    better than 100m: 100
    100m to 1km: 500
    1km to 10km: 5000
    10km to 100km: 50000
    worse than 100km: 500000
