application:
  # Geometry is a GeoJSON object
  geometry:
    type: Polygon
    coordinates: [[[43.24, -11.95],[50.50, -11.95],[50.50, -25.59],[43.24, -25.59],[43.24, -11.95]]]
  name: "Madagascar"
  layers:
  - name: "Regions"
    url: "http://esapp.unibe.ch/geoserver/spm/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "regions"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
  - name: "Districts"
    url: "http://esapp.unibe.ch/geoserver/spm/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "Districts"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]    
  - name: "Communes"
    url: "http://esapp.unibe.ch/geoserver/spm/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "communes"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
  - name: "Fokontany"
    url: "http://esapp.unibe.ch/geoserver/spm/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "Fokontany"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
  - name: "Accessability"
  - name: "Accessability"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "accessability"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.7
  - name: "Population Density 2008"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "lspop_2008"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Land Cover 2009"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "globcover_2009"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Cropland"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "gl_cropland"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Pasture Land"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "gl_pasture"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  spatial_accuracy:
    better than 100m: 100
    100m to 1km: 500
    1km to 10km: 5000
    10km to 100km: 50000
    worse than 100km: 500000
