application:
  geometry:
    type: Polygon
    coordinates: [[[100.081,13.9099],[107.635,13.9099],[107.635,22.509],[100.081,22.509],[100.081,13.9099]]]
  name: ສາທາລະນະລັດປະຊາທິປະໄຕ ປະຊາຊົນລາວ
  layers:
  - name: "Incidence of poverty"
    url: "https://sdi.cde.unibe.ch/geoserver/gwc/service/wms"
    wms_options:
    - epsg: 900913
    - format: "image/png8"
    - layers: "poverty_incidence"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [10018755, 181, 12801601, 3482189]
    - opacity: 0.7
  - name: "Accessibility to province capital"
    url: "https://sdi.cde.unibe.ch/geoserver/gwc/service/wms"
    wms_options:
    - epsg: 900913
    - format: "image/png8"
    - layers: "t_to_prov_capital_mean_min"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [10018755, 181, 12801601, 3482189]
    - opacity: 0.7
  - name: "Seasonal road accessibility"
    url: "https://sdi.cde.unibe.ch/geoserver/gwc/service/wms"
    wms_options:
    - epsg: 900913
    - format: "image/png8"
    - layers: "w_road_access"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [10018755, 181, 12801601, 3482189]
    - opacity: 0.7
  - name: "Population density"
    url: "https://sdi.cde.unibe.ch/geoserver/gwc/service/wms"
    wms_options:
    - epsg: 900913
    - format: "image/png8"
    - layers: "pop_density"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [10018755, 181, 12801601, 3482189]
    - opacity: 0.7
  # Share of households being farm household
  - name: Share of households being farm household
    url: "https://sdi.cde.unibe.ch/geoserver/gwc/service/wms"
    wms_options:
    - epsg: 900913
    - format: "image/png8"
    - layers: "w_pct_farmhh"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [10018755, 181, 12801601, 3482189]
    - opacity: 0.7
  # Percentage of economically active population
  - name: Percentage of economically active population
    url: "https://sdi.cde.unibe.ch/geoserver/gwc/service/wms"
    wms_options:
    - epsg: 900913
    - format: "image/png8"
    - layers: "pop_econ_active_pct"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [10018755, 181, 12801601, 3482189]
    - opacity: 0.7
  - name: "Global Land Cover 2009"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "globcover_2009"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Cropland"
    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "gl_cropland"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
#  - name: "Global Pasture Land"
#    url: "https://sdi.cde.unibe.ch/geoserver/lo/wms"
#    wms_options:
#    - epsg: 900913
#    - format: "image/jpeg"
#    - layers: "gl_pasture"
#    - transparent: true
#    ol_options:
#    - visibility: false
#    - isBaseLayer: false
#    - sphericalMercator: true
#    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
#    - opacity: 0.6
  spatial_accuracy:
    better than 100m: 100
    100m to 1km: 500
    1km to 10km: 5000
    10km to 100km: 50000
    worse than 100km: 500000
